### ISSUE TITLE
Incomplete Code?

### ISSUE THREAD

**Issue by bsilvereagle** [rmoehn/gnucash_autobudget#3]
The master branch doesn't contain a usable Python script. 

The other branch does, but it does not have a **main** function for the use case that is described in the README. 

Is there code missing? Additionally, has this been pushed to pip? Neither pip or pip2 could find it.

**Comment by rmoehn** [comment]
Hi! Thanks for checking this out! You're right, it's not finished. Recently I didn't have time to continue working on this, but I'm suffering from not being able to budget. If you have Python experience, you're welcome to contribute. I would show you around. Otherwise I hope I can make time for continuing development in one or two months.

For a start, I will add a note that this is doesn't work yet, so that people don't have to waste their time trying like you did.

**Comment by bsilvereagle** [comment]
I'll poke around and see what you've got so far. From my experience today, python+gnucash is a little bit of a bother. But, I like your approach and think it's probably the only way to get the type of budgeting we're after to play nicely in gnucash. 

I was just a little confused since the pip instructions made it looked like a finished product.

**Comment by rmoehn** [comment]
Yes, sorry for that! It's kind of unusual to write nice documentation before a program is working…

**Comment by rmoehn** [comment]
By the way, the code is on the branch `starting-out`. I didn't expect collaborators at this stage, so it's not too collaboratable.

**Comment by bsilvereagle** [comment]
I ended up getting a solution working for myself using ledger. If you're okay with using a cli utility operating on text files, it's worth looking into. 

Additionally, there is a $200USD bug bounty open to implement what you're trying to do in gnucash - https://wiki.gnucash.org/wiki/Bounty_Program#Eligible_Tasks

**Comment by rmoehn** [comment]
Interesting. The last resolutions are more than two years old, though, so I don't have much hope that anybody would implement budgeting soon. And I wouldn't be able to do it myself within reasonable time. I guess they're not looking for external Python solutions. ;-)

Unfortunately I only realized that ledger would be a good (better) alternative when I'd already migrated from YNAB to GnuCash and been using GnuCash for a while. Sure, there is a GnuCash → Ledger export program, but I have many two-currency transactions, so I expect that it won't work well. I'll give it a try before I continue GnuCash Autobudget, though. Ledger (hledger for me) looks really cool.

**Comment by rmoehn** [comment]
I tried the export and it looked pretty good. The thing is that I'd have write a hledger plugin that does something very similar to what GnuCash Autobudget will do. Admittedly in a more sane programming environment. I saw that ledger itself has some magic that you can use to insert virtual budget postings automatically, though.

At the moment I still don't have time to continue with GnuCash Autobudget. :-(

**Comment by bsilvereagle** [comment]
I'll write up a post on how I'm doing budgeting in ledger. I've been meaning to for weeks, but hopefully it'll get done in the next few days. No plugins necessary if virtual transactions are leveraged properly.

**Comment by rmoehn** [comment]
Sounds good! I know of these two ways:
- https://www.petekeen.net/program-your-finances-envelope-budgeting requires ledger magic, as noted above.
- https://gist.github.com/simonmichael/a1addcb652da4e78b183 associates the virtual budget accounts with an actual asset account or you have to add budget postings manually.

I'm curious what you've found. A solution that avoids both these problems?

**Comment by bsilvereagle** [comment]
Hmm, ledger magic is definitely in use in my method. Once setup, the magic is in the background and you use ledger normally. I'll have it up tomorrow. 

However, I do have budgeting categories tied to real accounts. For example, rent comes out of account X, food/utilities/gas/etc come from account Y. It shouldn't be a problem to disassociate the budget from the real account though. The incomplete article, just so you can get an idea of what I do at a very high level: http://frdmtoplay.com/envelope-budgeting-with-ledger/

If you follow the numbers, "Vacation" budget is tied to the Savings Account, and all other budgets are tied to the Checking Account. The values shown in those accounts are unbudgeted funds. 

If the idea isn't clear, it will when I get the full thing fleshed out. I've gone ahead and put the sample ledger file here if you want to take a look: https://gist.github.com/bsilvereagle/8b0bddd86232e02d181d65c5bc7abb15

There seems to be a lot of ledger magic going on, but in reality, it doesn't affect the day-to-day use at all. Income entries are standard income entries, and Expense entries are like expense entries. 

It'll all be made clear when I finish the post.

**Comment by rmoehn** [comment]
I get the idea. Thanks for pre-publishing! The problem is that I want to use hledger and hledger doesn't have automated transactions. Maybe I shouldn't be so fixed on hledger and just have an easy life instead. :-)

**Comment by bsilvereagle** [comment]
Oh! I didn't realize that, I thought they had feature parity. 

In that case, good luck. I don't imagine doing budgeting without automated transactions will be much fun. 

Edit: I finished up the post, but it's not going to be all that useful for you.

**Comment by rmoehn** [comment]
Haha, I think many people would be surprised if you told them that budgeting is fun even with automated transactions. ;-)

The author of hledger isn't sure whether adding automated transactions would be a good idea: https://github.com/simonmichael/hledger/issues/99

Thanks for the post anyway! I think it will help other people.

**Comment by bsilvereagle** [comment]
Hmm, I don't blame them for not wanting to tackle expression handling. 

If you find a way to do this style of budgeting within the constraints of hledger, I'd definitely be interested in reading about it.

**Comment by rmoehn** [comment]
Thanks! I was thinking of continuing GnuCash Autobudget when I have time again, but your comment made me change my mind. I'll have a look at writing a plugin for hledger first. Maybe it's much easier than messing with GnuCash!

**Comment by rmoehn** [comment]
I now use hledger with [hledger-rewrite](https://github.com/simonmichael/hledger/blob/master/bin/hledger-rewrite.hs) to automatically add budget postings. It works quite well. I just have to figure out a way to make it faster with large journal files and many expense accounts.

**Comment by bsilvereagle** [comment]
How convenient, my next blog post is going to be about breaking up large ledger files into annual (or monthly, etc) files to speed things up. 

So you run hledger-rewrite multiple times, once for every budget "envelope" ?

**Comment by rmoehn** [comment]
Hmm, I thought I would find the time to write up something, but that would take some largish blog post… I don't use hledger-rewrite at all anymore. After reading some of Ramit Sethi's material on personal finance I decided that I don't need budget accounts as detailed as expenses accounts. I only have a few budget accounts now. At the end of the month I calculate the balance on two categories of expenses – fun and non-fun – for that month and subtract it from the budget accounts all at once. The rest of the budget postings I add manually.

Probably you can't understand any of this. ;-) Explaining it well would take many more words.
